### ISSUE TITLE
Working on an update for 3.3.0 by any chance?

### ISSUE THREAD

**Issue by amandryka** [kokernutz/traktor-kontrol-screens#37]
Shows you how good your mod is when I'm freaking out with the default screens :)

**Comment by HaryShanthi** [comment]
Hey! Same request as "amandryka" if it would be possible to get a 3.3 version when your schedule allows as i miss ur mod. Thanks in advance

**Comment by bertpatroons** [comment]
+1

**Comment by slsilvia** [comment]
+1

**Comment by MrPatben8** [comment]
+1

**Comment by kokernutz** [comment]
Sorry y'all! I was going to do it this weekend but got sidetracked with wine.

I'm going to try and live stream me updating my mods tonight! No more alcohol until the mods are updated. :)

**Comment by MrPatben8** [comment]
@kokernutz I'll be tuning in :)

**Comment by kokernutz** [comment]
follow me on twitter @kokernutz 

or twitch.tv/kokernutz

i am not going to do it tonight (my day job sucked me in) but i did hook up my S5 to make sure that it still works and i am writing up an outline so i can do the livestream and make the changes as fast as i can. hopefully 30 minutes. 60 at most.

check back tomorrow!

**Comment by kokernutz** [comment]
> Thanks!
> Anyone knows where are these streams happening?
> 
> Also @kokernutz where would you recommend I start learning about qml scripting for the S5?

I'll give a little overview, but if you've done any programming at all I'm confident you can figure it out easily. (It's javascript.)

**Comment by MrPatben8** [comment]
Damn, I missed the live stream. Any idea when the update comes out? @kokernutz

**Comment by kokernutz** [comment]
I will work on it some more tomorrow... I was a little careless and f-ed something up. Will pick it back tomorrow night.

**Comment by MrPatben8** [comment]
Ah, alrighty then. Good luck!

**Comment by MrPatben8** [comment]
So I tried my luck updating it myself and I think I've got it working. @kokernutz

**Comment by slsilvia** [comment]
Is the 3.3.0 mod ready to roll?

**Comment by MrPatben8** [comment]
@slsilvia Almost, you can check out my fork here https://github.com/MrPatben8/traktor-kontrol-screens
It should be working with Traktor 3.3.0 plus some extra fixes and features
I'm currently adding some extra features so I'd suggest waiting a little before downloading it.
I'll let you guys know when it's done.

**Comment by yuletide** [comment]
@MrPatben8  Tried your fork (3.3.0 update branch?) but I'm having weird oscillating sounds and the controller doesn't start up. Maybe I missed something?

**Comment by MrPatben8** [comment]
@yuletide Hmm, that's strange. I have no explanation for the weird sounds, the mod should only modify the inputs (control surface) and the displays. As for the controller not starting up I'm not sure, perhaps I missed something in the update, but I did have a similar issue when I didn't copy all of the qml files correctly. Are you on Windows or MacOS?

**Comment by yuletide** [comment]
@MrPatben8 Just tried reinstalling by copying into `/qml` instead of replacing it but same issue (audio artifacts only happen when Master is set to 90%+). I'm on MacOS.

**Comment by MrPatben8** [comment]
@yuletide I'll take a look at it tomorrow but I can't test anything since I just own an S8. I'll see if I maybe missed anything obvious. Although usually when something isn't right with the mod it usually just crashes Traktor, so this behavior you're experiencing is unusual.

**Comment by MrPatben8** [comment]
@yuletide You could help me debugging. Install the mod except for the following files (keep the originals instead of replacing them):

- CSI/S4MK3/S4MK3Channel.qml
- CSI/S4MK3/S4MK3Deck.qml
- CSI/S4MK3/S4MK3Mixer.qml
- CSI/S4MK3/S4MK3Side.qml
- CSI/S4MK3/S4MK3TempoControl.qml
- CSI/S4MK3/S4MK3TransportButtons.qml
- Screens/S4MK3/ViewModels/DeckInfo.qml

Then one by one replace an original file with the modded version and restart Traktor until it no longer works, then let me know the last file that you replaced. This should help me pin-point where the issue is.

**Comment by slsilvia** [comment]
@MrPatben8 any update on the bugs?

**Comment by MrPatben8** [comment]
@slsilvia I believe most bugs have been fixed so the updated mod should be good to go, unless you are using an S4mk3. If you are, please follow my debug steps above and let me know what happens, that way I can solve those issues. There are still some small visual bugs that need to be fixed but they don't interfere with any functionality. I will get around to fixing them later today. You can find my fork here https://github.com/MrPatben8/traktor-kontrol-screens
If you run into any other issues please let me know.

**Comment by slsilvia** [comment]
just downloaded the new qml build and nothing worked, not even the change to the desktop UI. additionally, when plugged in, my S4MK3 did not respond at all.

**Comment by yuletide** [comment]
Sorry I ended up installing the other mod (browse mode!) for a gig Friday so haven’t had time to bug fix this one. That thing is legit...

**Comment by MrPatben8** [comment]
@slsilvia Are you downloading this mod or my fork? This mod is not working because it hasn't been updated yet. If you want the updated version of this mod you need to download my fork from here https://github.com/mrpatben8/traktor-kontrol-screens/

**Comment by slsilvia** [comment]
yeah, just download your fork. Changed the name of existing qml to qmlBackup, renamed your fork to qml, dropped it into the resources folder, opened Traktor and the waveforms/phase meter are still the same as default.

**Comment by MrPatben8** [comment]
@slsilvia Is the rest of the mod working?

**Comment by slsilvia** [comment]
@MrPatben8 no. It would appear not.

**Comment by kokernutz** [comment]
I just updated my repo. Please give it a whirl and let me know if you run into any problems.

**Comment by amandryka** [comment]
Thanks, seems to be working on S5.
