### ISSUE TITLE
Update for Traktor 3.11.0 by @JorgeHontoria - Browser Key Match Not Working

### ISSUE THREAD

**Issue by skymakai** [kokernutz/traktor-kontrol-screens#56]
Hello, @JorgeHontoria :) 
I recently found your fork (not committed yet, so I can't post an issue on your fork), and tested with the Kontrol S5.
I found that the key match indicator isn't working at all, and some odd visual glitches (see attached images)

https://github.com/kokernutz/traktor-kontrol-screens/assets/15059021/a1d96a71-20c7-4e17-9f51-a10ceacde24d

https://github.com/kokernutz/traktor-kontrol-screens/assets/15059021/13589e3e-a336-4eee-8ea7-77c4a3b389fd

**Comment by JorgeHontoria** [comment]
I think I've figured out what was going wrong. ".track.content.entry_key" becomes ".content.legacy_key".

**Comment by skymakai** [comment]
Thank you!  Do you have somewhere someone can send you a donation?

Unfortunately, looks like there's still a couple issues:
- We don't see a Key Match indicator next to the Key column.
- The whole BPM column is green, not just BPM matches.

Is the Prefs.qml still being referred to for custom preferences?  

![IMG_1846](https://github.com/kokernutz/traktor-kontrol-screens/assets/15059021/42700759-64a2-4c26-a8cb-97e4355aead6)

**Comment by JorgeHontoria** [comment]
Traktor S8 version 3.10.1.16
https://github.com/kokernutz/traktor-kontrol-screens/assets/6266381/6b3e6b2f-905d-4c30-9c80-8b4ded76783c

Source Code: https://github.com/JorgeHontoria/traktor-kontrol-screens

**Comment by skymakai** [comment]
I'm on Traktor version 3.11.0 (44).  Perhaps there's been more changes since Traktor version 3.10.1 (16).  I'll test that version against 3.11.0.  I never downloaded 3.10, so I'll have to request that download from Native Instruments.

But, it looks like it's working on the S8... so it may be something about the S5 specific files that needs to be updated.  
I figured the S8 and S5 use the same browser files.

**Comment by JorgeHontoria** [comment]
Supports Traktor 3.11.1.17 on S8. I have verified it. It is important to take into consideration that a deck must be active as MASTER (or activate AUTO).

I don't know how it will behave in D2 or S5. If someone donates me one I would make it functional without much delay.

**Comment by skymakai** [comment]
Updated to Traktor 3.11.1...Good news and bad news.  
- Key matching is working. ☺️
- BPM still shows colors incorrectly; some non-matching BPM are green and vice versa. (see image)

Almost there!  I'm happy to test/troubleshoot on the S5.  We can connect via Zoom and screen-share if needed.

![IMG_1850](https://github.com/kokernutz/traktor-kontrol-screens/assets/15059021/37dca4cb-3dbf-480f-93fc-e3d60c949b89)

**Comment by JorgeHontoria** [comment]
I have made many changes to integrate as many community features as possible. Please download the new version (for traktor 3.10.x and 3.11.x) from [New Version](https://github.com/JorgeHontoria/traktor-kontrol-screens), try it and let me know if you have any unresolved problems. 

Clicking on the star in the Git repository is appreciated.

**Comment by skymakai** [comment]
@JorgeHontoria Looking good.  
Almost there... only thing I see wrong is the BPM column is now "randomly colored" when a track's key matches.  (see image)

![IMG_1987](https://github.com/kokernutz/traktor-kontrol-screens/assets/15059021/64e0fb9e-a847-4641-b539-3430ff62661f)

**Comment by skymakai** [comment]
@JorgeHontoria 
Another example, showing master track's matching BPM: 

![IMG_1995](https://github.com/kokernutz/traktor-kontrol-screens/assets/15059021/668bfb97-180e-4987-8919-5e919fee46f0)

**Comment by JorgeHontoria** [comment]
Fixed

**Comment by skymakai** [comment]
@JorgeHontoria 
Fantastic work!  Be sure to post your PayPal or Venmo so we can support you.

Another issue:  Played tracks do not become 'dim' or indicate 'played'.  

Image below shows a 'played' track still the same grey color as the other library tracks.
![IMG_2006](https://github.com/kokernutz/traktor-kontrol-screens/assets/15059021/6f4a75cc-6679-4a98-a627-f50e37e38370)

**Comment by JorgeHontoria** [comment]
Customizing a plugin like this is a lot of work, but I like to do it. I know quite well the technology behind Traktor and I think I can do a good job. I accept the challenge, I'm up for it. To start with I have opened a Patreon to improve it [Patreon](https://www.patreon.com/traktorsimplescreen/). The first patrons will be able to define the following three features to implement (I'm already working on two interesting ones).

**Comment by skymakai** [comment]
@JorgeHontoria I've just subscribed.  Thank you for creating a way to support your work!

My hope is that the mod is maintained.  I'm interested in new features, but not at the cost of stability.  Note, I have tried the "Supreme Mod" and found that it changes too much from the defaults, and has graphical issues in the browser... likely because it's too bloated.

Did you see my previous reply about the Browser not dimming "played" tracks?

**Comment by MrPatben8** [comment]
Hi @JorgeHontoria I wanted to thank you for all the amazing work you've been doing with this project, giving it the love it deserves. I contributed a little to the original repo a few years ago and still utilize this mod religiously (I have an S8 and 2x D2s) so I'm very happy to see that you've been helping keep this mod alive for newer Traktor versions.
I have made some significant changes to my own fork of the mod (such as changing MixerFX flavor by using the FX channel assignment (arrow) buttons at the top of the S8 channels, amongst a bunch of other changes). And I wanted to know if you'd be open to discussing these modifications of mine and see if you might want to include them in your own fork of the mod. I think a lot of other users would benefit from these changes.

If you could enable the "Issues" section for your fork, I'd be happy to continue this conversation there.

Thanks again for your amazing work!

**Comment by JorgeHontoria** [comment]
I think the changes you made in the MOD are great that's why I have included part of them in the current fork (in the README.md I make reference to it). I would like to respect your work and include it for future versions. I would also like you to participate in the decisions of the future modifications (what better than you to decide the future of the MOD).

To verify that it is functionally to your liking, please download the current version of TraktorSimpleScreen from the Git repository and verifying the behavior of all your contributions (and some of mine and other community members) [Git TraktorSimpleScreen](https://github.com/JorgeHontoria/traktor-kontrol-screens). If you see any modification that is not included, let me know so I can include it.

In the future, the ideal is that we do the work in a coordinated way in the Patreon account (so that subscribers can decide on these issues), so I encourage you to subscribe and be part of the Early [Patreon TraktorSimpleScreen](https://www.patreon.com/TraktorSimpleScreen).

I think we can continue the conversation in this thread without problems.

Thank you very much for all you have contributed.

**Comment by MrPatben8** [comment]
@JorgeHontoria Sounds Great! See you over on Patreon!

**Comment by skymakai** [comment]
@JorgeHontoria The Patreon is a great way to converse, but we still need to enable "issues" on the Github repo.  There's no way to post pics of issues on Patreon.

Issue - Cue, Loops, OFF Markers (2 images):
![Cue, Loop, Off Marker](https://github.com/kokernutz/traktor-kontrol-screens/assets/15059021/7b251630-12ce-4772-8dfc-d4d04ea0ec65)
![Cue, Loop, Off Marker 2](https://github.com/kokernutz/traktor-kontrol-screens/assets/15059021/7c3efaee-8a2c-4ed7-a269-d2518f32d61d)

**Comment by JorgeHontoria** [comment]
Gracias, lo reviso y vemos como resolver el tema del reporte de bugs.

**Comment by JorgeHontoria** [comment]
Regarding the bugs, I think the best thing to do is to report them in the Git [Issues](https://github.com/JorgeHontoria/traktor-kontrol-screens/issues) repository, I have already activated it in the bugs section.

**Comment by skymakai** [comment]
Ah, good... thank you for enabling it.
